language: node_js # 언어는 node js
node_js:
  - '14.15.3' # node js 의 버전

env: # 환경변수
  - CI: false

branches: # 브랜치
  only:
    - release/0.1

cache:
  directories: # node module 을 캐시
    - node_modules
script:
  - yarn build # 보통 여기 테스트를 실행하는 스크립트가 들어감

before_deploy: # 배포전 배포파일을 압축
  - rm -rf node_modules
  - zip -r travis .
  - mkdir -p deploy
  - mv travis.zip deploy/travis.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: mapgoblin-deploy-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir : deploy
    wait-until-deployed: true
    on:
      repo: MapHackers/map-goblin-frontend
      branch: release/0.1

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: mapgoblin-deploy-bucket # S3 버킷
    key: travis.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: mapgoblin # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: mapgoblin-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: MapHackers/map-goblin-frontend
      branch: release/0.1

notifications:
  email:
    recipients:
      - 88dydfuf@naver.com